/**
 * @file
 *
 * @author CCHyper
 * @author OmniBlade
 *
 * @brief Static instances of template type objects.
 *
 * @copyright Chronoshift is free software: you can redistribute it and/or
 *            modify it under the terms of the GNU General Public License
 *            as published by the Free Software Foundation, either version
 *            2 of the License, or (at your option) any later version.
 *            A full copy of the GNU General Public License can be found in
 *            LICENSE
 */
#include "templatedata.h"

/**
 * For reference, the constructor argument order is;
 *
 * Type (TemplateType)
 * Theater
 * Name
 * UI Name
 * 
 */

// TemplateEmpty is a default template instance, it is never used.
const TemplateTypeClass TemplateEmpty(TEMPLATE_CLEAR, THEATER_BIT_ALL, "CLEAR1", TXT_CLEAR);

const TemplateTypeClass TemplateClear(TEMPLATE_CLEAR, THEATER_BIT_ALL, "CLEAR1", TXT_CLEAR);

const TemplateTypeClass TemplateRoad01(TEMPLATE_ROAD01, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D01", TXT_ROAD);
const TemplateTypeClass TemplateRoad02(TEMPLATE_ROAD02, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D02", TXT_ROAD);
const TemplateTypeClass TemplateRoad03(TEMPLATE_ROAD03, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D03", TXT_ROAD);
const TemplateTypeClass TemplateRoad04(TEMPLATE_ROAD04, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D04", TXT_ROAD);
const TemplateTypeClass TemplateRoad05(TEMPLATE_ROAD05, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D05", TXT_ROAD);
const TemplateTypeClass TemplateRoad06(TEMPLATE_ROAD06, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D06", TXT_ROAD);
const TemplateTypeClass TemplateRoad07(TEMPLATE_ROAD07, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D07", TXT_ROAD);
const TemplateTypeClass TemplateRoad08(TEMPLATE_ROAD08, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D08", TXT_ROAD);
const TemplateTypeClass TemplateRoad09(TEMPLATE_ROAD09, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D09", TXT_ROAD);
const TemplateTypeClass TemplateRoad10(TEMPLATE_ROAD10, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D10", TXT_ROAD);
const TemplateTypeClass TemplateRoad11(TEMPLATE_ROAD11, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D11", TXT_ROAD);
const TemplateTypeClass TemplateRoad12(TEMPLATE_ROAD12, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D12", TXT_ROAD);
const TemplateTypeClass TemplateRoad13(TEMPLATE_ROAD13, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D13", TXT_ROAD);
const TemplateTypeClass TemplateRoad14(TEMPLATE_ROAD14, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D14", TXT_ROAD);
const TemplateTypeClass TemplateRoad15(TEMPLATE_ROAD15, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D15", TXT_ROAD);
const TemplateTypeClass TemplateRoad16(TEMPLATE_ROAD16, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D16", TXT_ROAD);
const TemplateTypeClass TemplateRoad17(TEMPLATE_ROAD17, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D17", TXT_ROAD);
const TemplateTypeClass TemplateRoad18(TEMPLATE_ROAD18, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D18", TXT_ROAD);
const TemplateTypeClass TemplateRoad19(TEMPLATE_ROAD19, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D19", TXT_ROAD);
const TemplateTypeClass TemplateRoad20(TEMPLATE_ROAD20, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D20", TXT_ROAD);
const TemplateTypeClass TemplateRoad21(TEMPLATE_ROAD21, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D21", TXT_ROAD);
const TemplateTypeClass TemplateRoad22(TEMPLATE_ROAD22, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D22", TXT_ROAD);
const TemplateTypeClass TemplateRoad23(TEMPLATE_ROAD23, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D23", TXT_ROAD);
const TemplateTypeClass TemplateRoad24(TEMPLATE_ROAD24, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D24", TXT_ROAD);
const TemplateTypeClass TemplateRoad25(TEMPLATE_ROAD25, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D25", TXT_ROAD);
const TemplateTypeClass TemplateRoad26(TEMPLATE_ROAD26, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D26", TXT_ROAD);
const TemplateTypeClass TemplateRoad27(TEMPLATE_ROAD27, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D27", TXT_ROAD);
const TemplateTypeClass TemplateRoad28(TEMPLATE_ROAD28, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D28", TXT_ROAD);
const TemplateTypeClass TemplateRoad29(TEMPLATE_ROAD29, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D29", TXT_ROAD);
const TemplateTypeClass TemplateRoad30(TEMPLATE_ROAD30, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D30", TXT_ROAD);
const TemplateTypeClass TemplateRoad31(TEMPLATE_ROAD31, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D31", TXT_ROAD);
const TemplateTypeClass TemplateRoad32(TEMPLATE_ROAD32, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D32", TXT_ROAD);
const TemplateTypeClass TemplateRoad33(TEMPLATE_ROAD33, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D33", TXT_ROAD);
const TemplateTypeClass TemplateRoad34(TEMPLATE_ROAD34, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D34", TXT_ROAD);
const TemplateTypeClass TemplateRoad35(TEMPLATE_ROAD35, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D35", TXT_ROAD);
const TemplateTypeClass TemplateRoad36(TEMPLATE_ROAD36, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D36", TXT_ROAD);
const TemplateTypeClass TemplateRoad37(TEMPLATE_ROAD37, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D37", TXT_ROAD);
const TemplateTypeClass TemplateRoad38(TEMPLATE_ROAD38, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D38", TXT_ROAD);
const TemplateTypeClass TemplateRoad39(TEMPLATE_ROAD39, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D39", TXT_ROAD);
const TemplateTypeClass TemplateRoad40(TEMPLATE_ROAD40, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D40", TXT_ROAD);
const TemplateTypeClass TemplateRoad41(TEMPLATE_ROAD41, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D41", TXT_ROAD);
const TemplateTypeClass TemplateRoad42(TEMPLATE_ROAD42, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D42", TXT_ROAD);
const TemplateTypeClass TemplateRoad43(TEMPLATE_ROAD43, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D43", TXT_ROAD);
const TemplateTypeClass TemplateRoad44(TEMPLATE_ROAD44, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D44", TXT_ROAD);
const TemplateTypeClass TemplateRoad45(TEMPLATE_ROAD45, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "D45", TXT_ROAD);

const TemplateTypeClass TemplateWater(TEMPLATE_WATER, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "W1", TXT_WATER);
const TemplateTypeClass TemplateWater2(TEMPLATE_WATER2, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "W2", TXT_WATER);

const TemplateTypeClass TemplateShore01(TEMPLATE_SHORE01, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH01", TXT_SHORE);
const TemplateTypeClass TemplateShore02(TEMPLATE_SHORE02, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH02", TXT_SHORE);
const TemplateTypeClass TemplateShore03(TEMPLATE_SHORE03, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH03", TXT_SHORE);
const TemplateTypeClass TemplateShore04(TEMPLATE_SHORE04, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH04", TXT_SHORE);
const TemplateTypeClass TemplateShore05(TEMPLATE_SHORE05, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH05", TXT_SHORE);
const TemplateTypeClass TemplateShore06(TEMPLATE_SHORE06, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH06", TXT_SHORE);
const TemplateTypeClass TemplateShore07(TEMPLATE_SHORE07, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH07", TXT_SHORE);
const TemplateTypeClass TemplateShore08(TEMPLATE_SHORE08, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH08", TXT_SHORE);
const TemplateTypeClass TemplateShore09(TEMPLATE_SHORE09, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH09", TXT_SHORE);
const TemplateTypeClass TemplateShore10(TEMPLATE_SHORE10, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH10", TXT_SHORE);
const TemplateTypeClass TemplateShore11(TEMPLATE_SHORE11, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH11", TXT_SHORE);
const TemplateTypeClass TemplateShore12(TEMPLATE_SHORE12, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH12", TXT_SHORE);
const TemplateTypeClass TemplateShore13(TEMPLATE_SHORE13, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH13", TXT_SHORE);
const TemplateTypeClass TemplateShore14(TEMPLATE_SHORE14, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH14", TXT_SHORE);
const TemplateTypeClass TemplateShore15(TEMPLATE_SHORE15, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH15", TXT_SHORE);
const TemplateTypeClass TemplateShore16(TEMPLATE_SHORE16, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH16", TXT_SHORE);
const TemplateTypeClass TemplateShore17(TEMPLATE_SHORE17, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH17", TXT_SHORE);
const TemplateTypeClass TemplateShore18(TEMPLATE_SHORE18, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH18", TXT_SHORE);
const TemplateTypeClass TemplateShore19(TEMPLATE_SHORE19, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH19", TXT_SHORE);
const TemplateTypeClass TemplateShore20(TEMPLATE_SHORE20, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH20", TXT_SHORE);
const TemplateTypeClass TemplateShore21(TEMPLATE_SHORE21, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH21", TXT_SHORE);
const TemplateTypeClass TemplateShore22(TEMPLATE_SHORE22, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH22", TXT_SHORE);
const TemplateTypeClass TemplateShore23(TEMPLATE_SHORE23, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH23", TXT_SHORE);
const TemplateTypeClass TemplateShore24(TEMPLATE_SHORE24, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH24", TXT_SHORE);
const TemplateTypeClass TemplateShore25(TEMPLATE_SHORE25, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH25", TXT_SHORE);
const TemplateTypeClass TemplateShore26(TEMPLATE_SHORE26, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH26", TXT_SHORE);
const TemplateTypeClass TemplateShore27(TEMPLATE_SHORE27, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH27", TXT_SHORE);
const TemplateTypeClass TemplateShore28(TEMPLATE_SHORE28, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH28", TXT_SHORE);
const TemplateTypeClass TemplateShore29(TEMPLATE_SHORE29, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH29", TXT_SHORE);
const TemplateTypeClass TemplateShore30(TEMPLATE_SHORE30, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH30", TXT_SHORE);
const TemplateTypeClass TemplateShore31(TEMPLATE_SHORE31, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH31", TXT_SHORE);
const TemplateTypeClass TemplateShore32(TEMPLATE_SHORE32, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH32", TXT_SHORE);
const TemplateTypeClass TemplateShore33(TEMPLATE_SHORE33, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH33", TXT_SHORE);
const TemplateTypeClass TemplateShore34(TEMPLATE_SHORE34, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH34", TXT_SHORE);
const TemplateTypeClass TemplateShore35(TEMPLATE_SHORE35, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH35", TXT_SHORE);
const TemplateTypeClass TemplateShore36(TEMPLATE_SHORE36, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH36", TXT_SHORE);
const TemplateTypeClass TemplateShore37(TEMPLATE_SHORE37, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH37", TXT_SHORE);
const TemplateTypeClass TemplateShore38(TEMPLATE_SHORE38, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH38", TXT_SHORE);
const TemplateTypeClass TemplateShore39(TEMPLATE_SHORE39, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH39", TXT_SHORE);
const TemplateTypeClass TemplateShore40(TEMPLATE_SHORE40, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH40", TXT_SHORE);
const TemplateTypeClass TemplateShore41(TEMPLATE_SHORE41, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH41", TXT_SHORE);
const TemplateTypeClass TemplateShore42(TEMPLATE_SHORE42, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH42", TXT_SHORE);
const TemplateTypeClass TemplateShore43(TEMPLATE_SHORE43, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH43", TXT_SHORE);
const TemplateTypeClass TemplateShore44(TEMPLATE_SHORE44, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH44", TXT_SHORE);
const TemplateTypeClass TemplateShore45(TEMPLATE_SHORE45, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH45", TXT_SHORE);
const TemplateTypeClass TemplateShore46(TEMPLATE_SHORE46, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH46", TXT_SHORE);
const TemplateTypeClass TemplateShore47(TEMPLATE_SHORE47, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH47", TXT_SHORE);
const TemplateTypeClass TemplateShore48(TEMPLATE_SHORE48, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH48", TXT_SHORE);
const TemplateTypeClass TemplateShore49(TEMPLATE_SHORE49, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH49", TXT_SHORE);
const TemplateTypeClass TemplateShore50(TEMPLATE_SHORE50, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH50", TXT_SHORE);
const TemplateTypeClass TemplateShore51(TEMPLATE_SHORE51, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH51", TXT_SHORE);
const TemplateTypeClass TemplateShore52(TEMPLATE_SHORE52, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH52", TXT_SHORE);
const TemplateTypeClass TemplateShore53(TEMPLATE_SHORE53, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH53", TXT_SHORE);
const TemplateTypeClass TemplateShore54(TEMPLATE_SHORE54, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH54", TXT_SHORE);
const TemplateTypeClass TemplateShore55(TEMPLATE_SHORE55, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH55", TXT_SHORE);
const TemplateTypeClass TemplateShore56(TEMPLATE_SHORE56, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "SH56", TXT_SHORE);

const TemplateTypeClass TemplateBoulder1(TEMPLATE_BOULDER1, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "B1", TXT_SLOPE);
const TemplateTypeClass TemplateBoulder2(TEMPLATE_BOULDER2, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "B2", TXT_SLOPE);
const TemplateTypeClass TemplateBoulder3(TEMPLATE_BOULDER3, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "B3", TXT_SLOPE);
const TemplateTypeClass TemplateBoulder4(TEMPLATE_BOULDER4, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "B4", TXT_SLOPE);
const TemplateTypeClass TemplateBoulder5(TEMPLATE_BOULDER5, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "B5", TXT_SLOPE);
const TemplateTypeClass TemplateBoulder6(TEMPLATE_BOULDER6, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "B6", TXT_SLOPE);

const TemplateTypeClass TemplateSlope01(TEMPLATE_SLOPE01, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S01", TXT_SLOPE);
const TemplateTypeClass TemplateSlope02(TEMPLATE_SLOPE02, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S02", TXT_SLOPE);
const TemplateTypeClass TemplateSlope03(TEMPLATE_SLOPE03, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S03", TXT_SLOPE);
const TemplateTypeClass TemplateSlope04(TEMPLATE_SLOPE04, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S04", TXT_SLOPE);
const TemplateTypeClass TemplateSlope05(TEMPLATE_SLOPE05, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S05", TXT_SLOPE);
const TemplateTypeClass TemplateSlope06(TEMPLATE_SLOPE06, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S06", TXT_SLOPE);
const TemplateTypeClass TemplateSlope07(TEMPLATE_SLOPE07, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S07", TXT_SLOPE);
const TemplateTypeClass TemplateSlope08(TEMPLATE_SLOPE08, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S08", TXT_SLOPE);
const TemplateTypeClass TemplateSlope09(TEMPLATE_SLOPE09, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S09", TXT_SLOPE);
const TemplateTypeClass TemplateSlope10(TEMPLATE_SLOPE10, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S10", TXT_SLOPE);
const TemplateTypeClass TemplateSlope11(TEMPLATE_SLOPE11, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S11", TXT_SLOPE);
const TemplateTypeClass TemplateSlope12(TEMPLATE_SLOPE12, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S12", TXT_SLOPE);
const TemplateTypeClass TemplateSlope13(TEMPLATE_SLOPE13, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S13", TXT_SLOPE);
const TemplateTypeClass TemplateSlope14(TEMPLATE_SLOPE14, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S14", TXT_SLOPE);
const TemplateTypeClass TemplateSlope15(TEMPLATE_SLOPE15, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S15", TXT_SLOPE);
const TemplateTypeClass TemplateSlope16(TEMPLATE_SLOPE16, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S16", TXT_SLOPE);
const TemplateTypeClass TemplateSlope17(TEMPLATE_SLOPE17, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S17", TXT_SLOPE);
const TemplateTypeClass TemplateSlope18(TEMPLATE_SLOPE18, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S18", TXT_SLOPE);
const TemplateTypeClass TemplateSlope19(TEMPLATE_SLOPE19, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S19", TXT_SLOPE);
const TemplateTypeClass TemplateSlope20(TEMPLATE_SLOPE20, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S20", TXT_SLOPE);
const TemplateTypeClass TemplateSlope21(TEMPLATE_SLOPE21, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S21", TXT_SLOPE);
const TemplateTypeClass TemplateSlope22(TEMPLATE_SLOPE22, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S22", TXT_SLOPE);
const TemplateTypeClass TemplateSlope23(TEMPLATE_SLOPE23, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S23", TXT_SLOPE);
const TemplateTypeClass TemplateSlope24(TEMPLATE_SLOPE24, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S24", TXT_SLOPE);
const TemplateTypeClass TemplateSlope25(TEMPLATE_SLOPE25, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S25", TXT_SLOPE);
const TemplateTypeClass TemplateSlope26(TEMPLATE_SLOPE26, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S26", TXT_SLOPE);
const TemplateTypeClass TemplateSlope27(TEMPLATE_SLOPE27, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S27", TXT_SLOPE);
const TemplateTypeClass TemplateSlope28(TEMPLATE_SLOPE28, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S28", TXT_SLOPE);
const TemplateTypeClass TemplateSlope29(TEMPLATE_SLOPE29, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S29", TXT_SLOPE);
const TemplateTypeClass TemplateSlope30(TEMPLATE_SLOPE30, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S30", TXT_SLOPE);
const TemplateTypeClass TemplateSlope31(TEMPLATE_SLOPE31, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S31", TXT_SLOPE);
const TemplateTypeClass TemplateSlope32(TEMPLATE_SLOPE32, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S32", TXT_SLOPE);
const TemplateTypeClass TemplateSlope33(TEMPLATE_SLOPE33, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S33", TXT_SLOPE);
const TemplateTypeClass TemplateSlope34(TEMPLATE_SLOPE34, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S34", TXT_SLOPE);
const TemplateTypeClass TemplateSlope35(TEMPLATE_SLOPE35, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S35", TXT_SLOPE);
const TemplateTypeClass TemplateSlope36(TEMPLATE_SLOPE36, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S36", TXT_SLOPE);
const TemplateTypeClass TemplateSlope37(TEMPLATE_SLOPE37, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S37", TXT_SLOPE);
const TemplateTypeClass TemplateSlope38(TEMPLATE_SLOPE38, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "S38", TXT_SLOPE);

const TemplateTypeClass TemplatePatch01(TEMPLATE_PATCH01, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "P01", TXT_PATCH);
const TemplateTypeClass TemplatePatch02(TEMPLATE_PATCH02, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "P02", TXT_PATCH);
const TemplateTypeClass TemplatePatch03(TEMPLATE_PATCH03, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "P03", TXT_PATCH);
const TemplateTypeClass TemplatePatch04(TEMPLATE_PATCH04, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "P04", TXT_PATCH);
const TemplateTypeClass TemplatePatch07(TEMPLATE_PATCH07, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "P07", TXT_PATCH);
const TemplateTypeClass TemplatePatch08(TEMPLATE_PATCH08, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "P08", TXT_PATCH);
const TemplateTypeClass TemplatePatch13(TEMPLATE_PATCH13, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "P13", TXT_PATCH);
const TemplateTypeClass TemplatePatch14(TEMPLATE_PATCH14, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "P14", TXT_PATCH);
const TemplateTypeClass TemplatePatch15(TEMPLATE_PATCH15, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "P15", TXT_PATCH);

const TemplateTypeClass TemplateRiver01(TEMPLATE_RIVER01, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV01", TXT_RIVER);
const TemplateTypeClass TemplateRiver02(TEMPLATE_RIVER02, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV02", TXT_RIVER);
const TemplateTypeClass TemplateRiver03(TEMPLATE_RIVER03, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV03", TXT_RIVER);
const TemplateTypeClass TemplateRiver04(TEMPLATE_RIVER04, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV04", TXT_RIVER);
const TemplateTypeClass TemplateRiver05(TEMPLATE_RIVER05, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV05", TXT_RIVER);
const TemplateTypeClass TemplateRiver06(TEMPLATE_RIVER06, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV06", TXT_RIVER);
const TemplateTypeClass TemplateRiver07(TEMPLATE_RIVER07, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV07", TXT_RIVER);
const TemplateTypeClass TemplateRiver08(TEMPLATE_RIVER08, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV08", TXT_RIVER);
const TemplateTypeClass TemplateRiver09(TEMPLATE_RIVER09, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV09", TXT_RIVER);
const TemplateTypeClass TemplateRiver10(TEMPLATE_RIVER10, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV10", TXT_RIVER);
const TemplateTypeClass TemplateRiver11(TEMPLATE_RIVER11, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV11", TXT_RIVER);
const TemplateTypeClass TemplateRiver12(TEMPLATE_RIVER12, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV12", TXT_RIVER);
const TemplateTypeClass TemplateRiver13(TEMPLATE_RIVER13, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV13", TXT_RIVER);
const TemplateTypeClass TemplateRiver14(TEMPLATE_RIVER14, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV14", TXT_RIVER);
const TemplateTypeClass TemplateRiver15(TEMPLATE_RIVER15, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RV15", TXT_RIVER);

const TemplateTypeClass TemplateFord1(TEMPLATE_FORD1, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "FORD1", TXT_RIVER);
const TemplateTypeClass TemplateFord2(TEMPLATE_FORD2, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "FORD2", TXT_RIVER);

const TemplateTypeClass TemplateFalls1(TEMPLATE_FALLS1, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "FALLS1", TXT_RIVER);
const TemplateTypeClass TemplateFalls1a(TEMPLATE_FALLS1A, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "FALLS1A", TXT_RIVER);
const TemplateTypeClass TemplateFalls2(TEMPLATE_FALLS2, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "FALLS2", TXT_RIVER);
const TemplateTypeClass TemplateFalls2a(TEMPLATE_FALLS2A, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "FALLS2A", TXT_RIVER);

const TemplateTypeClass TemplateBridge1x(TEMPLATE_BRIDGE1X, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BRIDGE1X", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge1(TEMPLATE_BRIDGE1, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BRIDGE1", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge1h(TEMPLATE_BRIDGE1H, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BRIDGE1H", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge1d(TEMPLATE_BRIDGE1D, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BRIDGE1D", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge2x(TEMPLATE_BRIDGE2X, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BRIDGE2X", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge2(TEMPLATE_BRIDGE2, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BRIDGE2", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge2h(TEMPLATE_BRIDGE2H, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BRIDGE2H", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge2d(TEMPLATE_BRIDGE2D, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BRIDGE2D", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge1ax(TEMPLATE_BRIDGE1AX, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR1X", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge1a(TEMPLATE_BRIDGE1A, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR1A", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge1b(TEMPLATE_BRIDGE1B, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR1B", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge1c(TEMPLATE_BRIDGE1C, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR1C", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge2ax(TEMPLATE_BRIDGE2AX, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR2X", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge2a(TEMPLATE_BRIDGE2A, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR2A", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge2b(TEMPLATE_BRIDGE2B, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR2B", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge2c(TEMPLATE_BRIDGE2C, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR2C", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge3a(TEMPLATE_BRIDGE3A, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR3A", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge3b(TEMPLATE_BRIDGE3B, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR3B", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge3c(TEMPLATE_BRIDGE3C, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR3C", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge3d(TEMPLATE_BRIDGE3D, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR3D", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge3e(TEMPLATE_BRIDGE3E, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR3E", TXT_BRIDGE);
const TemplateTypeClass TemplateBridge3f(TEMPLATE_BRIDGE3F, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "BR3F", TXT_BRIDGE);

const TemplateTypeClass TemplateShoreCliff01(TEMPLATE_SHORECLIFF01, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC01", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff02(TEMPLATE_SHORECLIFF02, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC02", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff03(TEMPLATE_SHORECLIFF03, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC03", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff04(TEMPLATE_SHORECLIFF04, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC04", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff05(TEMPLATE_SHORECLIFF05, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC05", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff06(TEMPLATE_SHORECLIFF06, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC06", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff07(TEMPLATE_SHORECLIFF07, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC07", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff08(TEMPLATE_SHORECLIFF08, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC08", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff09(TEMPLATE_SHORECLIFF09, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC09", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff10(TEMPLATE_SHORECLIFF10, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC10", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff11(TEMPLATE_SHORECLIFF11, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC11", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff12(TEMPLATE_SHORECLIFF12, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC12", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff13(TEMPLATE_SHORECLIFF13, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC13", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff14(TEMPLATE_SHORECLIFF14, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC14", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff15(TEMPLATE_SHORECLIFF15, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC15", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff16(TEMPLATE_SHORECLIFF16, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC16", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff17(TEMPLATE_SHORECLIFF17, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC17", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff18(TEMPLATE_SHORECLIFF18, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC18", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff19(TEMPLATE_SHORECLIFF19, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC19", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff20(TEMPLATE_SHORECLIFF20, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC20", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff21(TEMPLATE_SHORECLIFF21, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC21", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff22(TEMPLATE_SHORECLIFF22, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC22", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff23(TEMPLATE_SHORECLIFF23, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC23", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff24(TEMPLATE_SHORECLIFF24, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC24", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff25(TEMPLATE_SHORECLIFF25, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC25", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff26(TEMPLATE_SHORECLIFF26, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC26", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff27(TEMPLATE_SHORECLIFF27, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC27", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff28(TEMPLATE_SHORECLIFF28, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC28", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff29(TEMPLATE_SHORECLIFF29, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC29", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff30(TEMPLATE_SHORECLIFF30, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC30", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff31(TEMPLATE_SHORECLIFF31, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC31", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff32(TEMPLATE_SHORECLIFF32, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC32", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff33(TEMPLATE_SHORECLIFF33, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC33", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff34(TEMPLATE_SHORECLIFF34, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC34", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff35(TEMPLATE_SHORECLIFF35, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC35", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff36(TEMPLATE_SHORECLIFF36, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC36", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff37(TEMPLATE_SHORECLIFF37, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC37", TXT_SHORE);
const TemplateTypeClass TemplateShoreCliff38(TEMPLATE_SHORECLIFF38, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "WC38", TXT_SHORE);

const TemplateTypeClass TemplateRough01(TEMPLATE_ROUGH01, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RF01", TXT_ROCK);
const TemplateTypeClass TemplateRough02(TEMPLATE_ROUGH02, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RF02", TXT_ROCK);
const TemplateTypeClass TemplateRough03(TEMPLATE_ROUGH03, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RF03", TXT_ROCK);
const TemplateTypeClass TemplateRough04(TEMPLATE_ROUGH04, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RF04", TXT_ROCK);
const TemplateTypeClass TemplateRough05(TEMPLATE_ROUGH05, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RF05", TXT_ROCK);
const TemplateTypeClass TemplateRough06(TEMPLATE_ROUGH06, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RF06", TXT_ROCK);
const TemplateTypeClass TemplateRough07(TEMPLATE_ROUGH07, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RF07", TXT_ROCK);
const TemplateTypeClass TemplateRough08(TEMPLATE_ROUGH08, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RF08", TXT_ROCK);
const TemplateTypeClass TemplateRough09(TEMPLATE_ROUGH09, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RF09", TXT_ROCK);
const TemplateTypeClass TemplateRough10(TEMPLATE_ROUGH10, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RF10", TXT_ROCK);
const TemplateTypeClass TemplateRough11(TEMPLATE_ROUGH11, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RF11", TXT_ROCK);

const TemplateTypeClass TemplateRiverCliff01(TEMPLATE_RIVERCLIFF01, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RC01", TXT_RIVER);
const TemplateTypeClass TemplateRiverCliff02(TEMPLATE_RIVERCLIFF02, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RC02", TXT_RIVER);
const TemplateTypeClass TemplateRiverCliff03(TEMPLATE_RIVERCLIFF03, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RC03", TXT_RIVER);
const TemplateTypeClass TemplateRiverCliff04(TEMPLATE_RIVERCLIFF04, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "RC04", TXT_RIVER);

const TemplateTypeClass TemplateF01(TEMPLATE_F01, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "F01", TXT_RIVER);
const TemplateTypeClass TemplateF02(TEMPLATE_F02, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "F02", TXT_RIVER);
const TemplateTypeClass TemplateF03(TEMPLATE_F03, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "F03", TXT_RIVER);
const TemplateTypeClass TemplateF04(TEMPLATE_F04, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "F04", TXT_RIVER);
const TemplateTypeClass TemplateF05(TEMPLATE_F05, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "F05", TXT_RIVER);
const TemplateTypeClass TemplateF06(TEMPLATE_F06, (THEATER_BIT_TEMPERATE | THEATER_BIT_SNOW), "F06", TXT_RIVER);

const TemplateTypeClass TemplateArrow01(TEMPLATE_ARRO0001, THEATER_BIT_INTERIOR, "ARRO0001", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow02(TEMPLATE_ARRO0002, THEATER_BIT_INTERIOR, "ARRO0002", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow03(TEMPLATE_ARRO0003, THEATER_BIT_INTERIOR, "ARRO0003", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow04(TEMPLATE_ARRO0004, THEATER_BIT_INTERIOR, "ARRO0004", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow05(TEMPLATE_ARRO0005, THEATER_BIT_INTERIOR, "ARRO0005", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow06(TEMPLATE_ARRO0006, THEATER_BIT_INTERIOR, "ARRO0006", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow07(TEMPLATE_ARRO0007, THEATER_BIT_INTERIOR, "ARRO0007", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow08(TEMPLATE_ARRO0008, THEATER_BIT_INTERIOR, "ARRO0008", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow09(TEMPLATE_ARRO0009, THEATER_BIT_INTERIOR, "ARRO0009", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow10(TEMPLATE_ARRO0010, THEATER_BIT_INTERIOR, "ARRO0010", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow11(TEMPLATE_ARRO0011, THEATER_BIT_INTERIOR, "ARRO0011", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow12(TEMPLATE_ARRO0012, THEATER_BIT_INTERIOR, "ARRO0012", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow13(TEMPLATE_ARRO0013, THEATER_BIT_INTERIOR, "ARRO0013", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow14(TEMPLATE_ARRO0014, THEATER_BIT_INTERIOR, "ARRO0014", TXT_INTERIOR);
const TemplateTypeClass TemplateArrow15(TEMPLATE_ARRO0015, THEATER_BIT_INTERIOR, "ARRO0015", TXT_INTERIOR);

const TemplateTypeClass TemplateFLOR0001(TEMPLATE_FLOR0001, THEATER_BIT_INTERIOR, "FLOR0001", TXT_INTERIOR);
const TemplateTypeClass TemplateFLOR0002(TEMPLATE_FLOR0002, THEATER_BIT_INTERIOR, "FLOR0002", TXT_INTERIOR);
const TemplateTypeClass TemplateFLOR0003(TEMPLATE_FLOR0003, THEATER_BIT_INTERIOR, "FLOR0003", TXT_INTERIOR);
const TemplateTypeClass TemplateFLOR0004(TEMPLATE_FLOR0004, THEATER_BIT_INTERIOR, "FLOR0004", TXT_INTERIOR);
const TemplateTypeClass TemplateFLOR0005(TEMPLATE_FLOR0005, THEATER_BIT_INTERIOR, "FLOR0005", TXT_INTERIOR);
const TemplateTypeClass TemplateFLOR0006(TEMPLATE_FLOR0006, THEATER_BIT_INTERIOR, "FLOR0006", TXT_INTERIOR);
const TemplateTypeClass TemplateFLOR0007(TEMPLATE_FLOR0007, THEATER_BIT_INTERIOR, "FLOR0007", TXT_INTERIOR);

const TemplateTypeClass TemplateGFLR0001(TEMPLATE_GFLR0001, THEATER_BIT_INTERIOR, "GFLR0001", TXT_INTERIOR);
const TemplateTypeClass TemplateGFLR0002(TEMPLATE_GFLR0002, THEATER_BIT_INTERIOR, "GFLR0002", TXT_INTERIOR);
const TemplateTypeClass TemplateGFLR0003(TEMPLATE_GFLR0003, THEATER_BIT_INTERIOR, "GFLR0003", TXT_INTERIOR);
const TemplateTypeClass TemplateGFLR0004(TEMPLATE_GFLR0004, THEATER_BIT_INTERIOR, "GFLR0004", TXT_INTERIOR);
const TemplateTypeClass TemplateGFLR0005(TEMPLATE_GFLR0005, THEATER_BIT_INTERIOR, "GFLR0005", TXT_INTERIOR);
const TemplateTypeClass TemplateGSTR0001(TEMPLATE_GSTR0001, THEATER_BIT_INTERIOR, "GSTR0001", TXT_INTERIOR);
const TemplateTypeClass TemplateGSTR0002(TEMPLATE_GSTR0002, THEATER_BIT_INTERIOR, "GSTR0002", TXT_INTERIOR);
const TemplateTypeClass TemplateGSTR0003(TEMPLATE_GSTR0003, THEATER_BIT_INTERIOR, "GSTR0003", TXT_INTERIOR);
const TemplateTypeClass TemplateGSTR0004(TEMPLATE_GSTR0004, THEATER_BIT_INTERIOR, "GSTR0004", TXT_INTERIOR);
const TemplateTypeClass TemplateGSTR0005(TEMPLATE_GSTR0005, THEATER_BIT_INTERIOR, "GSTR0005", TXT_INTERIOR);
const TemplateTypeClass TemplateGSTR0006(TEMPLATE_GSTR0006, THEATER_BIT_INTERIOR, "GSTR0006", TXT_INTERIOR);
const TemplateTypeClass TemplateGSTR0007(TEMPLATE_GSTR0007, THEATER_BIT_INTERIOR, "GSTR0007", TXT_INTERIOR);
const TemplateTypeClass TemplateGSTR0008(TEMPLATE_GSTR0008, THEATER_BIT_INTERIOR, "GSTR0008", TXT_INTERIOR);
const TemplateTypeClass TemplateGSTR0009(TEMPLATE_GSTR0009, THEATER_BIT_INTERIOR, "GSTR0009", TXT_INTERIOR);
const TemplateTypeClass TemplateGSTR0010(TEMPLATE_GSTR0010, THEATER_BIT_INTERIOR, "GSTR0010", TXT_INTERIOR);
const TemplateTypeClass TemplateGSTR0011(TEMPLATE_GSTR0011, THEATER_BIT_INTERIOR, "GSTR0011", TXT_INTERIOR);

const TemplateTypeClass TemplateLWAL0001(TEMPLATE_LWAL0001, THEATER_BIT_INTERIOR, "LWAL0001", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0002(TEMPLATE_LWAL0002, THEATER_BIT_INTERIOR, "LWAL0002", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0003(TEMPLATE_LWAL0003, THEATER_BIT_INTERIOR, "LWAL0003", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0004(TEMPLATE_LWAL0004, THEATER_BIT_INTERIOR, "LWAL0004", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0005(TEMPLATE_LWAL0005, THEATER_BIT_INTERIOR, "LWAL0005", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0006(TEMPLATE_LWAL0006, THEATER_BIT_INTERIOR, "LWAL0006", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0007(TEMPLATE_LWAL0007, THEATER_BIT_INTERIOR, "LWAL0007", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0008(TEMPLATE_LWAL0008, THEATER_BIT_INTERIOR, "LWAL0008", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0009(TEMPLATE_LWAL0009, THEATER_BIT_INTERIOR, "LWAL0009", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0010(TEMPLATE_LWAL0010, THEATER_BIT_INTERIOR, "LWAL0010", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0011(TEMPLATE_LWAL0011, THEATER_BIT_INTERIOR, "LWAL0011", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0012(TEMPLATE_LWAL0012, THEATER_BIT_INTERIOR, "LWAL0012", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0013(TEMPLATE_LWAL0013, THEATER_BIT_INTERIOR, "LWAL0013", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0014(TEMPLATE_LWAL0014, THEATER_BIT_INTERIOR, "LWAL0014", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0015(TEMPLATE_LWAL0015, THEATER_BIT_INTERIOR, "LWAL0015", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0016(TEMPLATE_LWAL0016, THEATER_BIT_INTERIOR, "LWAL0016", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0017(TEMPLATE_LWAL0017, THEATER_BIT_INTERIOR, "LWAL0017", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0018(TEMPLATE_LWAL0018, THEATER_BIT_INTERIOR, "LWAL0018", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0019(TEMPLATE_LWAL0019, THEATER_BIT_INTERIOR, "LWAL0019", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0020(TEMPLATE_LWAL0020, THEATER_BIT_INTERIOR, "LWAL0020", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0021(TEMPLATE_LWAL0021, THEATER_BIT_INTERIOR, "LWAL0021", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0022(TEMPLATE_LWAL0022, THEATER_BIT_INTERIOR, "LWAL0022", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0023(TEMPLATE_LWAL0023, THEATER_BIT_INTERIOR, "LWAL0023", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0024(TEMPLATE_LWAL0024, THEATER_BIT_INTERIOR, "LWAL0024", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0025(TEMPLATE_LWAL0025, THEATER_BIT_INTERIOR, "LWAL0025", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0026(TEMPLATE_LWAL0026, THEATER_BIT_INTERIOR, "LWAL0026", TXT_INTERIOR);
const TemplateTypeClass TemplateLWAL0027(TEMPLATE_LWAL0027, THEATER_BIT_INTERIOR, "LWAL0027", TXT_INTERIOR);

const TemplateTypeClass TemplateStripe01(TEMPLATE_STRP0001, THEATER_BIT_INTERIOR, "STRP0001", TXT_INTERIOR);
const TemplateTypeClass TemplateStripe02(TEMPLATE_STRP0002, THEATER_BIT_INTERIOR, "STRP0002", TXT_INTERIOR);
const TemplateTypeClass TemplateStripe03(TEMPLATE_STRP0003, THEATER_BIT_INTERIOR, "STRP0003", TXT_INTERIOR);
const TemplateTypeClass TemplateStripe04(TEMPLATE_STRP0004, THEATER_BIT_INTERIOR, "STRP0004", TXT_INTERIOR);
const TemplateTypeClass TemplateStripe05(TEMPLATE_STRP0005, THEATER_BIT_INTERIOR, "STRP0005", TXT_INTERIOR);
const TemplateTypeClass TemplateStripe06(TEMPLATE_STRP0006, THEATER_BIT_INTERIOR, "STRP0006", TXT_INTERIOR);
const TemplateTypeClass TemplateStripe07(TEMPLATE_STRP0007, THEATER_BIT_INTERIOR, "STRP0007", TXT_INTERIOR);
const TemplateTypeClass TemplateStripe08(TEMPLATE_STRP0008, THEATER_BIT_INTERIOR, "STRP0008", TXT_INTERIOR);
const TemplateTypeClass TemplateStripe09(TEMPLATE_STRP0009, THEATER_BIT_INTERIOR, "STRP0009", TXT_INTERIOR);
const TemplateTypeClass TemplateStripe10(TEMPLATE_STRP0010, THEATER_BIT_INTERIOR, "STRP0010", TXT_INTERIOR);
const TemplateTypeClass TemplateStripe11(TEMPLATE_STRP0011, THEATER_BIT_INTERIOR, "STRP0011", TXT_INTERIOR);

const TemplateTypeClass TemplateWall01(TEMPLATE_WALL0001, THEATER_BIT_INTERIOR, "WALL0001", TXT_INTERIOR);
const TemplateTypeClass TemplateWall02(TEMPLATE_WALL0002, THEATER_BIT_INTERIOR, "WALL0002", TXT_INTERIOR);
const TemplateTypeClass TemplateWall03(TEMPLATE_WALL0003, THEATER_BIT_INTERIOR, "WALL0003", TXT_INTERIOR);
const TemplateTypeClass TemplateWall04(TEMPLATE_WALL0004, THEATER_BIT_INTERIOR, "WALL0004", TXT_INTERIOR);
const TemplateTypeClass TemplateWall05(TEMPLATE_WALL0005, THEATER_BIT_INTERIOR, "WALL0005", TXT_INTERIOR);
const TemplateTypeClass TemplateWall06(TEMPLATE_WALL0006, THEATER_BIT_INTERIOR, "WALL0006", TXT_INTERIOR);
const TemplateTypeClass TemplateWall07(TEMPLATE_WALL0007, THEATER_BIT_INTERIOR, "WALL0007", TXT_INTERIOR);
const TemplateTypeClass TemplateWall08(TEMPLATE_WALL0008, THEATER_BIT_INTERIOR, "WALL0008", TXT_INTERIOR);
const TemplateTypeClass TemplateWall09(TEMPLATE_WALL0009, THEATER_BIT_INTERIOR, "WALL0009", TXT_INTERIOR);
const TemplateTypeClass TemplateWall10(TEMPLATE_WALL0010, THEATER_BIT_INTERIOR, "WALL0010", TXT_INTERIOR);
const TemplateTypeClass TemplateWall11(TEMPLATE_WALL0011, THEATER_BIT_INTERIOR, "WALL0011", TXT_INTERIOR);
const TemplateTypeClass TemplateWall12(TEMPLATE_WALL0012, THEATER_BIT_INTERIOR, "WALL0012", TXT_INTERIOR);
const TemplateTypeClass TemplateWall13(TEMPLATE_WALL0013, THEATER_BIT_INTERIOR, "WALL0013", TXT_INTERIOR);
const TemplateTypeClass TemplateWall14(TEMPLATE_WALL0014, THEATER_BIT_INTERIOR, "WALL0014", TXT_INTERIOR);
const TemplateTypeClass TemplateWall15(TEMPLATE_WALL0015, THEATER_BIT_INTERIOR, "WALL0015", TXT_INTERIOR);
const TemplateTypeClass TemplateWall16(TEMPLATE_WALL0016, THEATER_BIT_INTERIOR, "WALL0016", TXT_INTERIOR);
const TemplateTypeClass TemplateWall17(TEMPLATE_WALL0017, THEATER_BIT_INTERIOR, "WALL0017", TXT_INTERIOR);
const TemplateTypeClass TemplateWall18(TEMPLATE_WALL0018, THEATER_BIT_INTERIOR, "WALL0018", TXT_INTERIOR);
const TemplateTypeClass TemplateWall19(TEMPLATE_WALL0019, THEATER_BIT_INTERIOR, "WALL0019", TXT_INTERIOR);
const TemplateTypeClass TemplateWall20(TEMPLATE_WALL0020, THEATER_BIT_INTERIOR, "WALL0020", TXT_INTERIOR);
const TemplateTypeClass TemplateWall21(TEMPLATE_WALL0021, THEATER_BIT_INTERIOR, "WALL0021", TXT_INTERIOR);
const TemplateTypeClass TemplateWall22(TEMPLATE_WALL0022, THEATER_BIT_INTERIOR, "WALL0022", TXT_INTERIOR);
const TemplateTypeClass TemplateWall23(TEMPLATE_WALL0023, THEATER_BIT_INTERIOR, "WALL0023", TXT_INTERIOR);
const TemplateTypeClass TemplateWall24(TEMPLATE_WALL0024, THEATER_BIT_INTERIOR, "WALL0024", TXT_INTERIOR);
const TemplateTypeClass TemplateWall25(TEMPLATE_WALL0025, THEATER_BIT_INTERIOR, "WALL0025", TXT_INTERIOR);
const TemplateTypeClass TemplateWall26(TEMPLATE_WALL0026, THEATER_BIT_INTERIOR, "WALL0026", TXT_INTERIOR);
const TemplateTypeClass TemplateWall27(TEMPLATE_WALL0027, THEATER_BIT_INTERIOR, "WALL0027", TXT_INTERIOR);
const TemplateTypeClass TemplateWall28(TEMPLATE_WALL0028, THEATER_BIT_INTERIOR, "WALL0028", TXT_INTERIOR);
const TemplateTypeClass TemplateWall29(TEMPLATE_WALL0029, THEATER_BIT_INTERIOR, "WALL0029", TXT_INTERIOR);
const TemplateTypeClass TemplateWall30(TEMPLATE_WALL0030, THEATER_BIT_INTERIOR, "WALL0030", TXT_INTERIOR);
const TemplateTypeClass TemplateWall31(TEMPLATE_WALL0031, THEATER_BIT_INTERIOR, "WALL0031", TXT_INTERIOR);
const TemplateTypeClass TemplateWall32(TEMPLATE_WALL0032, THEATER_BIT_INTERIOR, "WALL0032", TXT_INTERIOR);
const TemplateTypeClass TemplateWall33(TEMPLATE_WALL0033, THEATER_BIT_INTERIOR, "WALL0033", TXT_INTERIOR);
const TemplateTypeClass TemplateWall34(TEMPLATE_WALL0034, THEATER_BIT_INTERIOR, "WALL0034", TXT_INTERIOR);
const TemplateTypeClass TemplateWall35(TEMPLATE_WALL0035, THEATER_BIT_INTERIOR, "WALL0035", TXT_INTERIOR);
const TemplateTypeClass TemplateWall36(TEMPLATE_WALL0036, THEATER_BIT_INTERIOR, "WALL0036", TXT_INTERIOR);
const TemplateTypeClass TemplateWall37(TEMPLATE_WALL0037, THEATER_BIT_INTERIOR, "WALL0037", TXT_INTERIOR);
const TemplateTypeClass TemplateWall38(TEMPLATE_WALL0038, THEATER_BIT_INTERIOR, "WALL0038", TXT_INTERIOR);
const TemplateTypeClass TemplateWall39(TEMPLATE_WALL0039, THEATER_BIT_INTERIOR, "WALL0039", TXT_INTERIOR);
const TemplateTypeClass TemplateWall40(TEMPLATE_WALL0040, THEATER_BIT_INTERIOR, "WALL0040", TXT_INTERIOR);
const TemplateTypeClass TemplateWall41(TEMPLATE_WALL0041, THEATER_BIT_INTERIOR, "WALL0041", TXT_INTERIOR);
const TemplateTypeClass TemplateWall42(TEMPLATE_WALL0042, THEATER_BIT_INTERIOR, "WALL0042", TXT_INTERIOR);
const TemplateTypeClass TemplateWall43(TEMPLATE_WALL0043, THEATER_BIT_INTERIOR, "WALL0043", TXT_INTERIOR);
const TemplateTypeClass TemplateWall44(TEMPLATE_WALL0044, THEATER_BIT_INTERIOR, "WALL0044", TXT_INTERIOR);
const TemplateTypeClass TemplateWall45(TEMPLATE_WALL0045, THEATER_BIT_INTERIOR, "WALL0045", TXT_INTERIOR);
const TemplateTypeClass TemplateWall46(TEMPLATE_WALL0046, THEATER_BIT_INTERIOR, "WALL0046", TXT_INTERIOR);
const TemplateTypeClass TemplateWall47(TEMPLATE_WALL0047, THEATER_BIT_INTERIOR, "WALL0047", TXT_INTERIOR);
const TemplateTypeClass TemplateWall48(TEMPLATE_WALL0048, THEATER_BIT_INTERIOR, "WALL0048", TXT_INTERIOR);
const TemplateTypeClass TemplateWall49(TEMPLATE_WALL0049, THEATER_BIT_INTERIOR, "WALL0049", TXT_INTERIOR);

const TemplateTypeClass TemplateXtra01(TEMPLATE_XTRA0001, THEATER_BIT_INTERIOR, "XTRA0001", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra02(TEMPLATE_XTRA0002, THEATER_BIT_INTERIOR, "XTRA0002", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra03(TEMPLATE_XTRA0003, THEATER_BIT_INTERIOR, "XTRA0003", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra04(TEMPLATE_XTRA0004, THEATER_BIT_INTERIOR, "XTRA0004", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra05(TEMPLATE_XTRA0005, THEATER_BIT_INTERIOR, "XTRA0005", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra06(TEMPLATE_XTRA0006, THEATER_BIT_INTERIOR, "XTRA0006", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra07(TEMPLATE_XTRA0007, THEATER_BIT_INTERIOR, "XTRA0007", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra08(TEMPLATE_XTRA0008, THEATER_BIT_INTERIOR, "XTRA0008", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra09(TEMPLATE_XTRA0009, THEATER_BIT_INTERIOR, "XTRA0009", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra10(TEMPLATE_XTRA0010, THEATER_BIT_INTERIOR, "XTRA0010", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra11(TEMPLATE_XTRA0011, THEATER_BIT_INTERIOR, "XTRA0011", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra12(TEMPLATE_XTRA0012, THEATER_BIT_INTERIOR, "XTRA0012", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra13(TEMPLATE_XTRA0013, THEATER_BIT_INTERIOR, "XTRA0013", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra14(TEMPLATE_XTRA0014, THEATER_BIT_INTERIOR, "XTRA0014", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra15(TEMPLATE_XTRA0015, THEATER_BIT_INTERIOR, "XTRA0015", TXT_INTERIOR);
const TemplateTypeClass TemplateXtra16(TEMPLATE_XTRA0016, THEATER_BIT_INTERIOR, "XTRA0016", TXT_INTERIOR);

const TemplateTypeClass TemplateAntHill(TEMPLATE_ANTHILL, THEATER_BIT_TEMPERATE, "HILL01", TXT_ROCK);
